### ISSUE TITLE
Programmatically editing nav files

### ISSUE THREAD

**Issue by alexiscoutinho** [shqke/nav_test#1]
Is it possible to programmatically edit a nav file? Not only would this help to keep track of what was changed and to avoid accidents, but it would also allow edit replays like in git merges. My motivation is the issue that different nav files cannot be easily combined. For example, if there are multiple PRs with nav changes on a single file, any update of it in master would render the propositions incompatible and all their changes would need to be manually redone. If all PR changes prior to the `nav_analyze` could be replayed on another base mesh, it would be dope.

This is something for the future though as there is no real demand right now and rarely there will be multiple simultaneous large works on a single file. But it's still a nice thought experiment.

**Comment by shqke** [comment]
This repository exists to display changes and confirm integrity on modified NAV files. While it's can be possible to perform changes and write them back, the process will be tiresome.

What you probably seek for is [vscript solution](https://developer.valvesoftware.com/wiki/List_of_L4D2_Script_Functions#TerrorNavArea). Given an entry point in vscript (game event will probably suit better), you can edit attributes of navigation-related structure, override their connections and so on.

Can do so from a function named `DoMapSpawnFixes` (may change in the future) within file `scripts/vscripts/community/usercustom/MAPNAME.nut`, use [this example](https://github.com/Tsuey/L4D2-Community-Update/blob/7be814ec505e4152133cec36e5a08e2ab049f6a4/root/scripts/vscripts/community/maps/c2m2_fairgrounds.nut#L173-L180). A function will be called once on a level init.

**Comment by alexiscoutinho** [comment]
However, from what I knew, those vscript functions are quite limited. They can't create, delete, split nav areas and ladders, corner lower and other detailed nav area tuning. But the vscript functions are helpful for now. I think they should be preferred whenever possible to avoid the problems I mentioned previously.

**Comment by shqke** [comment]
I will try to add something handy to be used to postprocess NAV files, but I also think that you should propose missing features to be added as natives into the game. 😃

**Comment by alexiscoutinho** [comment]
Do you mean simple propositions that only change connections and attributes (that could be implemented with vscript only) should still ideally be proposed as natives? Presumably because at least the diff would be done programmatically?

**Comment by shqke** [comment]
No, I meant to [add them into the game](https://github.com/Tsuey/L4D2-Community-Update/issues/new), since their existence would make sense.
